/**
 * One-sentence genre descriptions.
 * Hand-written because Spotify provides zero genre metadata.
 * Covers all PROBE_GENRES + SPOTIFY_GENRES seed list.
 */

export const GENRE_DESCRIPTIONS: Record<string, string> = {
  // ─── Core genres ────────────────────────────────────────────
  'rock': 'Guitar-driven energy that reshaped the 20th century and never really stopped.',
  'pop': 'Melody-first, hook-heavy music engineered to live in your head rent-free.',
  'hip-hop': 'Beats, bars, and storytelling born from block parties in the Bronx.',
  'r-n-b': 'Smooth vocals over groove-heavy production — the soul of modern pop.',
  'electronic': 'Synthesizers and drum machines building worlds without a single guitar.',
  'indie': 'The sound of doing it yourself before anyone told you that you could.',
  'alternative': 'Too weird for mainstream, too catchy for underground — the sweet spot.',
  'jazz': 'Improvisation as conversation — musicians thinking out loud together.',
  'soul': 'Raw emotion delivered straight from the chest, usually over organ and horns.',
  'folk': 'Acoustic storytelling passed down through campfires and coffee shops.',
  'country': 'Heartbreak, highways, and honesty set to steel guitar and fiddle.',
  'metal': 'Distortion cranked to the point where the amp becomes a weapon.',
  'punk': 'Three chords, maximum volume, zero permission needed.',
  'blues': 'The original language of musical pain — everything else borrowed from here.',
  'funk': 'The one where the bass player is the real lead singer.',
  'classical': 'Centuries of composed music that still sounds like the future sometimes.',
  'reggae': 'Offbeat rhythms and conscious lyrics that traveled from Kingston to everywhere.',
  'latin': 'A continent of rhythms — cumbia, bossa, salsa, reggaeton, and beyond.',

  // ─── Electronic subgenres ───────────────────────────────────
  'house': 'Four-on-the-floor kick drums invented in Chicago basements.',
  'ambient': 'Music designed to fill a room like light — present but not demanding.',
  'disco': 'Glitter, groove, and the radical act of dancing through the 70s.',
  'dance': 'If it makes strangers move in sync, it belongs here.',
  'synth-pop': 'New wave meets neon — synthesizers doing what guitars used to.',
  'techno': 'Relentless machine music forged in Detroit and unleashed on Berlin.',
  'trance': 'Hypnotic builds and euphoric drops designed to alter your state.',
  'edm': 'The festival-sized umbrella for anything electronic with a drop.',
  'deep-house': 'House music that chose mood over muscle.',
  'progressive-house': 'Patient builds that reward you for staying on the dance floor.',
  'drum-and-bass': 'Breakbeats at 170 BPM — the sound of caffeine becoming music.',
  'dubstep': 'Bass so low your chest becomes a subwoofer.',
  'breakbeat': 'Chopped-up drums that refuse to land where you expect.',
  'electro': 'Sharp, robotic funk — the missing link between Kraftwerk and hip-hop.',
  'idm': 'Electronic music for people who think dancing is too simple.',
  'minimal-techno': 'The art of building a universe from almost nothing.',
  'detroit-techno': 'Futurism and soul colliding on the assembly line.',
  'chicago-house': 'Where house music was born — gospel energy meets drum machines.',
  'hardstyle': 'Thundering kicks at 150 BPM for people who find techno too gentle.',
  'post-dubstep': 'What happened when dubstep grew up and got introspective.',
  'club': 'Whatever the DJ plays at 2 AM that keeps everyone moving.',

  // ─── Rock subgenres ─────────────────────────────────────────
  'new-wave': '80s art-school kids making angular pop with synthesizers and eyeliner.',
  'post-punk': 'Punk grew up, got darker, and discovered reverb.',
  'shoegaze': 'Walls of guitar noise so thick you can swim in them.',
  'grunge': 'Flannel, feedback, and the disillusionment of a generation.',
  'lo-fi': 'Imperfection as an aesthetic — tape hiss is a feature, not a bug.',
  'alt-rock': 'The 90s radio dial between too weird and not weird enough.',
  'hard-rock': 'Rock with the volume knob broken off at 11.',
  'psych-rock': 'What happens when rock discovers delay pedals and expanded consciousness.',
  'garage': 'Raw, unpolished rock made in actual garages (or at least that energy).',
  'power-pop': 'Crunchy guitars and hooks so perfect they should be illegal.',
  'punk-rock': 'Fast, loud, and done before you finished reading this sentence.',
  'rock-n-roll': 'The original rebellion — where everything in this list started.',
  'rockabilly': 'Elvis-era energy — slicked hair, upright bass, and swagger.',
  'emo': 'Feelings turned to 11 with guitars and confessional lyrics.',
  'goth': 'Dark romance, reverb, and the beauty of wearing all black.',
  'industrial': 'Machines and distortion weaponized into aggressive sound sculptures.',
  'hardcore': 'Punk but faster, louder, and angrier — vocals optional, intensity required.',
  'metalcore': 'Where metal\'s heaviness meets hardcore\'s raw energy at full speed.',
  'grindcore': 'Songs shorter than their titles, played at inhuman speed.',

  // ─── Metal subgenres ────────────────────────────────────────
  'black-metal': 'Tremolo picking, blast beats, and the frozen forests of Scandinavia.',
  'death-metal': 'Guttural vocals and technical brutality elevated to an art form.',
  'heavy-metal': 'The original loud — Iron Maiden, Judas Priest, and the gods that followed.',

  // ─── Soul / R&B family ──────────────────────────────────────
  'neo-soul': 'Soul music reborn through hip-hop\'s lens — warm, jazzy, and deeply human.',
  'trip-hop': 'Downtempo beats and dark atmospheres from the streets of Bristol.',
  'gospel': 'Music that speaks to something higher, powered by voices that prove it.',

  // ─── Folk / Country family ──────────────────────────────────
  'acoustic': 'Unplugged and unfiltered — just the instrument and the room.',
  'bluegrass': 'Appalachian string virtuosity at speeds that shouldn\'t be possible.',
  'honky-tonk': 'The sound of a dive bar jukebox at its most honest.',
  'singer-songwriter': 'One voice, one perspective, one guitar — the most intimate format.',

  // ─── Latin / World ──────────────────────────────────────────
  'afrobeat': 'Fela Kuti\'s legacy — polyrhythmic grooves that could last an hour and still feel short.',
  'ska': 'Upbeat offbeats that traveled from Jamaica to punk clubs worldwide.',
  'bossanova': 'Brazilian jazz meets the beach — elegant, understated, hypnotic.',
  'dancehall': 'Jamaican party music — riddims, toasting, and maximum energy.',
  'reggaeton': 'Latin urban beats that conquered the planet one dembow rhythm at a time.',
  'salsa': 'Cuban rhythms and New York attitude combined into pure dance fuel.',
  'samba': 'The heartbeat of Brazilian Carnival — percussion, joy, and movement.',
  'tango': 'Argentine passion expressed through dance, bandoneón, and dramatic pauses.',
  'forro': 'Northeastern Brazilian dance music — accordion-driven and impossible to sit still to.',
  'sertanejo': 'Brazilian country music — romantic, massive, and everywhere in Brazil.',
  'pagode': 'The laid-back cousin of samba — built for backyard hangouts.',
  'mpb': 'Música Popular Brasileira — where Brazilian art and pop blur beautifully.',

  // ─── Asian pop ──────────────────────────────────────────────
  'k-pop': 'Precision-engineered pop spectacles from South Korea that conquered the world.',
  'j-pop': 'Bright, melodic Japanese pop with an ear for unexpected hooks.',
  'j-rock': 'Japanese rock with a flair for the dramatic and technically ambitious.',
  'j-dance': 'High-energy Japanese dance music — neon-lit and irresistible.',
  'j-idol': 'Japanese idol-group pop — choreographed charm and devoted fanbases.',
  'cantopop': 'Cantonese pop from Hong Kong — lush melodies and cinematic emotion.',
  'mandopop': 'Mandarin-language pop spanning ballads to dance — massive across Asia.',

  // ─── Mood / Activity ───────────────────────────────────────
  'chill': 'The musical equivalent of a deep breath.',
  'happy': 'Dopamine in audio form.',
  'sad': 'Permission to feel everything at once.',
  'sleep': 'Designed to guide you somewhere softer.',
  'study': 'Background music that respects your focus.',
  'work-out': 'BPM-matched motivation for when willpower isn\'t enough.',
  'rainy-day': 'The soundtrack to watching the world slow down through a window.',
  'road-trip': 'Windows-down, volume-up, singing-with-strangers energy.',
  'summer': 'Warm air, long days, and the feeling that nothing ends.',
  'party': 'The playlist that turns strangers into friends by the second song.',
  'romance': 'Music that makes you want to text someone you shouldn\'t.',

  // ─── Other / Regional ──────────────────────────────────────
  'anime': 'High-energy themes that make opening credits an event.',
  'british': 'The sound of the UK — from Beatles jangle to grime basslines.',
  'brazil': 'A musical universe unto itself — tropicália to funk carioca.',
  'comedy': 'Music that\'s in on the joke.',
  'disney': 'Orchestral magic and the songs that shaped your childhood.',
  'dub': 'Reggae sent through a mixing board and returned as pure atmosphere.',
  'french': 'From chanson to French touch — style is always the point.',
  'german': 'Kraftwerk started it, Berlin kept it going, and the world caught up.',
  'groove': 'Whatever it is that makes your head nod involuntarily.',
  'guitar': 'Six strings and infinite possibilities.',
  'indian': 'Ragas, Bollywood, and rhythmic traditions spanning millennia.',
  'iranian': 'Persian musical traditions — ornate melodies and poetic depth.',
  'kids': 'Music that respects small ears and big imaginations.',
  'children': 'Playful sounds for the youngest listeners.',
  'malay': 'Malaysian pop and traditional music with a Southeast Asian warmth.',
  'movies': 'The scores and themes that made the scenes unforgettable.',
  'soundtracks': 'Music that was written to make you feel something about something else.',
  'show-tunes': 'Broadway\'s gift to anyone who\'s ever sung in the shower.',
  'new-age': 'Synthesized serenity for meditation, massage, and late-night contemplation.',
  'new-release': 'Whatever just dropped — genre TBD.',
  'opera': 'The original multimedia experience — drama, voice, and orchestra at full scale.',
  'philippines-opm': 'Original Pilipino Music — heartfelt ballads and feel-good pop.',
  'piano': 'The most versatile instrument given the spotlight it deserves.',
  'pop-film': 'Pop songs written for the big screen — catchier because the stakes are higher.',
  'songwriter': 'Craft-first music where the lyric always leads.',
  'spanish': 'From flamenco to modern pop — passion is the common thread.',
  'swedish': 'The country that exports pop perfection like other nations export oil.',
  'turkish': 'Where Eastern melodies meet Western production — haunting and rhythmic.',
  'world-music': 'The catch-all that means "not from here" — endlessly worth exploring.',

  // ─── Additional genres that might appear in probe results ──
  'indie-pop': 'Indie\'s cheerful sibling — jangly guitars and melodies that sparkle.',
  'dream-pop': 'Ethereal vocals floating on shimmering waves of reverb.',
};
